# Introduction to tensors

## Creating a tensor

In [146]:
import torch

In [147]:
# Scalar

scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [148]:
# Get dimension of tensor
print(scalar.ndim)

0


In [149]:
## Get tensor item (only works with scalar)
print(scalar.item())

7


In [150]:
# Vector

vector = torch.tensor([1, 2])
print(vector)
# >>> tensor([1, 2])

tensor([1, 2])


In [151]:
MATRIX = torch.tensor([[1, 2], [3, 4]])
print(MATRIX.ndim)

2


In [152]:
print(MATRIX.shape)

torch.Size([2, 2])


In [153]:
#Tensor

TENSOR = torch.tensor([
    [
        [1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]
    ]
])

print(TENSOR.ndim)

3


In [154]:
print(TENSOR.shape)

torch.Size([1, 3, 3])


## Random Tensors

In [155]:
random_tensor = torch.randn(3, 4)
print(random_tensor)

tensor([[ 2.2785, -0.5739,  0.4202,  0.0198],
        [-0.3095,  0.4839, -1.1727,  0.0644],
        [ 1.3278,  0.1791,  1.2715,  0.2707]])


In [156]:
print(random_tensor.ndim)

2


In [157]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))  # color channels (R, G, B), height, width
print(random_image_size_tensor.shape)

torch.Size([3, 224, 224])


In [158]:
print(random_image_size_tensor.ndim)

3


## Zeros and ones tensors

In [159]:
zeros = torch.zeros(3, 4)
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [160]:
ones = torch.ones(3, 4)
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [161]:
print(ones.dtype)

torch.float32


## Creating a range of tensors and tensors-like

In [162]:
one_to_ten = torch.arange(0, 10)

In [163]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)

## Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning :
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [164]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # What datatype is the tensor (ex : float32, float16...)
                               device=None,  # What device is your tensor on
                               requires_grad=False)  # Whether to track gradients with these tensors operations
float_32_tensor.dtype

torch.float32

In [165]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [166]:
float_16_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [167]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [168]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`


In [169]:
# Create a tensor
some_tensor = torch.randn(3, 4)
print(some_tensor)

tensor([[-0.3475,  0.6816, -0.9945,  1.2280],
        [ 0.2656,  0.9277,  0.3166, -0.5748],
        [-1.3255,  0.2509, -0.0172, -0.7320]])


In [170]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")


tensor([[-0.3475,  0.6816, -0.9945,  1.2280],
        [ 0.2656,  0.9277,  0.3166, -0.5748],
        [-1.3255,  0.2509, -0.0172, -0.7320]])
Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [171]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [172]:
# Multiply tensor
tensor * 10

tensor([10, 20, 30])

In [173]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [174]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning :

1. Element-wise multiplicatioon
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to statisfy:
1. The **inner dimension** must match:
* `(3, 2) @ (3, 2)` won't work -> inner dimension : (3, **2**) @ (**3**, 2)
* `'(2, 3) @ (3, 2)` will work -> inner dimension : (2, **3**) @ (**3**, 2)
* `'(3, 2) @ (2, 3)` will work -> inner dimension : (3, **2**) @ (**2**, 3)

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [175]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[1.2954, 0.3227, 0.6196],
        [0.7923, 0.1579, 0.3764],
        [0.9421, 0.2911, 0.4543]])

In [176]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [177]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [178]:
# Matrix multiplication by hand
print(tensor)
1*1 + 2*2 + 3*3


tensor([1, 2, 3])


14

In [179]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 0 ns


In [180]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most common errors in deep learning: shape errors

In [181]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [38]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [44]:
tensor_B.shape

torch.Size([3, 2])

In [45]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [52]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Orginal shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\n Output shape: {output.shape}")

Orginal shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

 Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [62]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [56]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [57]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [59]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [60]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [63]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [64]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the origingal tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze  - remove alls '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swaped) in a certain way

In [144]:
# Creating a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [145]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9) # Multiplication must be equal to size (1 * 9 = 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [146]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [147]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [149]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [151]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [157]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [160]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.randn(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [182]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [183]:
# Let's index on our new tensor
print(x[0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [184]:
# Let's index on the middle bracket (dim=1)
print(x[0][0])

tensor([1, 2, 3])


In [185]:
# Let's index of the most inner bracket (last dimension)
print(x[0][0][0])

tensor(1)


In [186]:
# You can also use ":" to select "all" of a target dimension
print(x[:, 0])

tensor([[1, 2, 3]])


In [187]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
print(x[:, :, 1])

tensor([[2, 5, 8]])


In [188]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
print(x[:, 1,  1])

tensor([5])


In [189]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
print(x[0, 0, :])

tensor([1, 2, 3])


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [1]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [2]:
# Change the value of array, what will do to `tensor`
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [4]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [5]:
numpy_tensor.dtype

dtype('float32')

In [6]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reprodicibility (trying to take random out of random) / Pseudo aléatoire

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [24]:
import torch

# Create two random tensors
random_tensor_A = torch.randn(3, 4)
random_tensor_B = torch.randn(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[-1.0002, -0.0244,  0.2497, -1.7517],
        [-0.1309,  1.4378, -0.1544, -0.2853],
        [-0.1389, -0.8561, -0.5364, -1.0440]])
tensor([[ 1.2561,  0.4627, -0.3151,  0.5482],
        [ 0.0369, -0.8128,  0.0121, -0.6397],
        [ 0.6416, -0.5964,  0.7355,  0.0723]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [16]:
# Let's make some random but reproducible tensors / Pseudo aléatoire
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED) # Work for one tensor
random_tensor_C = torch.randn(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.randn(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_D == random_tensor_C)

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])
tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPU = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good.


In [3]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:
https://pytorch.org/docs/stable/notes/cuda.html#device-agnostic-code

-> Run on GPU if available, else default to CPU

In [4]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [5]:
# Count numbers of devices
torch.cuda.device_count()

1

## Puting tensors (and models) on the GPU

The reason we want our tensors/mmodels on the GPU is because using a GPU results in faster computations.

In [7]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

In [9]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [10]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
print(tensor_back_on_cpu)

[1 2 3]
